### ISSUE TITLE
Chart config option not work correctly

### ISSUE THREAD

**Issue by hooopo** [pingcap/pingcap.github.io#128]
<img width="933" alt="image" src="https://github.com/pingcap/ossinsight-lite/assets/63877/128f4f3b-0f65-49ce-9581-56e8002770ba">

<img width="983" alt="image" src="https://github.com/pingcap/ossinsight-lite/assets/63877/daf7dcdd-0b21-4a2b-961a-3e81570adfbb">

1. the config for chart can not change, or when it changed, but chart not change together.
2. the y value of the chart display wrong.

sql for debug:

```sql
SELECT
    TIMESTAMPDIFF(YEAR, created_at, CURDATE()) AS years_ago,
    COUNT(*) AS num_users
FROM
    users
JOIN
    starred_repos ON users.id = starred_repos.user_id
GROUP BY
    years_ago
ORDER BY
    years_ago ASC;
```

**Comment by 634750802** [comment]
```
933410-fc2a705a967a6f9f.js:9 Uncaught TypeError: Cannot use 'in' operator to search for 'eventPhase' in category
    at 7896-64186b2222716838.js:1:936
    at Object.current (7896-64186b2222716838.js:1:2231)
    at Object.current (layout-040b3d7eebd75593.js:1:6253)
    at 3412-79a9ee1399bef40f.js:1:4062
    at Object.onValueChange (3412-79a9ee1399bef40f.js:1:4527)
    at C (3803-2056de7050ead8e3.js:1:20527)
    at 3412-79a9ee1399bef40f.js:1:269
    at Object.ab (f3933410-fc2a705a967a6f9f.js:9:70769)
    at aC (f3933410-fc2a705a967a6f9f.js:9:70923)
    at f3933410-fc2a705a967a6f9f.js:9:137512
（
```
